### ISSUE TITLE
what is "Bob" in this context?

### ISSUE THREAD

**Issue by guettli** [linbuxiao/Bob2Anki#1]
what is "Bob" in this context?

**Comment by linbuxiao** [comment]
https://github.com/ripperhe/Bob 

Bob is a translation software used on Mac.

Bob2Anki is a tool that helps me export the translated words to Anki, a software designed to aid in memory retention.

**Comment by linbuxiao** [comment]
Just out of curiosity, how did you discover this demo? Hahaha, it was a byproduct of my process of learning the Go programming language. If I were to write it again now, I would probably use Python or Ruby.

**Comment by guettli** [comment]
I was looking for a library to access Anki files via Golang.
